# Generated by Django 5.1 on 2024-08-17 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('images', '0002_alter_userimage_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumimage',
            unique_together={('image', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='albumuser',
            unique_together={('album', 'user')},
        ),
    ]
